name: esr
channels:
  - conda-forge
  - nvidia
dependencies:
  - scipy=1.10.1
  - pip=24.0
  - numpy=1.24.4
  - matplotlib=3.5.3
  - dm-haiku=0.0.12
  - tqdm=4.66.2
  - wandb=0.16.5
  - imageio=2.34.0
  - pygame=2.5.2
  - cudnn
  - cudatoolkit
  - cuda-nvcc
  - pip:
    - jax==0.4.28
    - jaxlib==0.4.28+cuda12.cudnn89
    - simple-pytree==0.2.2
    - imageio==2.34.0
    - moviepy==1.0.3
    - distrax==0.1.5
    - gym==0.26.2
    - gymnax==0.0.8
    - jaxmarl==0.0.2
    - tensorflow-probability==0.24.0
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
